spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_URI}
          predicates:
            - Path=/api/v1/auth/**

        - id: balance-service
          uri: ${BALANCE_URI}
          predicates:
            - Path=/api/v1/balance/**
          filters:
            - name: AuthenticationFilter

        - id: transaction-service
          uri: ${TRANSACTION_URI}
          predicates:
            - Path=/api/v1/transaction/**
          filters:
            - name: AuthenticationFilter

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway

auth:
  service:
    url: ${AUTH_URI}