server:
  port: 8081

spring:
  application:
    name: auth-service

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  config:
    import: optional:file:.env[.properties]
  profiles:
    active: production

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

base:
  url: ${BASE_URL}

balance:
  service:
    url: ${BALANCE_SERVICE_URL}

verification:
  token:
    expiration: 24